services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Пробрасываем порт приложения на хост
    volumes:
      - ./target:/app  # Монтируем папку target, чтобы приложение использовало актуальный JAR
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/menucraft
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: menupass
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=menucraft'
      - 'POSTGRES_PASSWORD=menupass'
      - 'POSTGRES_USER=admin'
    ports:
      - '59870:5432'
